apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: code-remote

resources:
  - namespace.yaml
  - api/
  - executor/

commonLabels:
  app.kubernetes.io/part-of: code-remote
  app.kubernetes.io/managed-by: kustomize
