apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - networkpolicy.yaml
  - runtimeclass.yaml

commonLabels:
  app.kubernetes.io/name: executor
  app.kubernetes.io/component: sandbox
